# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: python-calculator-app
  labels:
    app: python-calculator-app
spec:
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: python-calculator-app
  type: NodePort
